"""add_permissions_and_user_fields

Revision ID: 6e9603f7cfca
Revises: 1c5eea688df6
Create Date: 2026-10-05 22:11:19.916017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9603f7cfca'
down_revision: Union[str, None] = '1c5eea688df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_roles_code', ['code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_auth_user_id', ['auth_user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_auth_user_id', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('auth_user_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roles_code', type_='unique')
        batch_op.drop_column('code')

    op.drop_table('role_permissions')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
