"""add_workflow_state_machine_and_audit_hash_chain

Revision ID: 7db6414754c1
Revises: e05ed49c7e7f
Create Date: 2026-10-05 23:46:52.763904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db6414754c1'
down_revision: Union[str, None] = 'e05ed49c7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('required_role', sa.String(), nullable=False),
    sa.Column('required_permission', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_exceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('reporting_period_id', sa.String(), nullable=False),
    sa.Column('source_record_type', sa.String(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_exceptions_reporting_period_id'), ['reporting_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_exceptions_scope_id'), ['scope_id'], unique=False)

    op.create_table('approval_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_actions_submission_id'), ['submission_id'], unique=False)

    op.create_table('submission_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_versions_submission_id'), ['submission_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scope_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('previous_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('event_hash', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_event_hash'), ['event_hash'], unique=False)

    with op.batch_alter_table('energy_records', schema=None) as batch_op:
        batch_op.alter_column('scope2_co2e_tonnes',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('energy_gj',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('factor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('factor_version',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('fuel_records', schema=None) as batch_op:
        batch_op.alter_column('scope1_co2e_tonnes',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('factor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('factor_version',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_records', schema=None) as batch_op:
        batch_op.alter_column('factor_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('factor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('scope1_co2e_tonnes',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('energy_records', schema=None) as batch_op:
        batch_op.alter_column('factor_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('factor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('energy_gj',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('scope2_co2e_tonnes',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_hash'))
        batch_op.drop_column('event_hash')
        batch_op.drop_column('previous_hash')
        batch_op.drop_column('scope_id')
        batch_op.drop_column('scope_type')

    with op.batch_alter_table('submission_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_versions_submission_id'))

    op.drop_table('submission_versions')
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_actions_submission_id'))
        batch_op.drop_index(batch_op.f('ix_approval_actions_created_at'))

    op.drop_table('approval_actions')
    with op.batch_alter_table('compliance_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_exceptions_scope_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_exceptions_reporting_period_id'))

    op.drop_table('compliance_exceptions')
    op.drop_table('workflow_transitions')
    # ### end Alembic commands ###
