"""add_procurement_governance_and_csr_tables

Revision ID: ad6af777783a
Revises: b28d21a8f0de
Create Date: 2026-10-06 00:06:42.179466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6af777783a'
down_revision: Union[str, None] = 'b28d21a8f0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('csr_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_program_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_category_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['csr_program_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('governance_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('board_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_date', sa.String(), nullable=True),
    sa.Column('weblink', sa.String(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('grievance_redressal_defined', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_policies_policy_code'), ['policy_code'], unique=True)

    op.create_table('social_impact_indicators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('indicator_type', sa.String(), nullable=True),
    sa.Column('baseline_allowed', sa.Boolean(), nullable=True),
    sa.Column('target_allowed', sa.Boolean(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stakeholders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stakeholder_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_msme', sa.Boolean(), nullable=True),
    sa.Column('msme_type', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('annual_spend_inr_cr', sa.Float(), nullable=True),
    sa.Column('esg_audit_status', sa.String(), nullable=True),
    sa.Column('esg_score', sa.Float(), nullable=True),
    sa.Column('iso_14001_certified', sa.Boolean(), nullable=True),
    sa.Column('iso_45001_certified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_vendor_code'), ['vendor_code'], unique=True)

    op.create_table('ethics_grievances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reporting_period_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('complaints_received', sa.Integer(), nullable=True),
    sa.Column('complaints_resolved', sa.Integer(), nullable=True),
    sa.Column('complaints_pending', sa.Integer(), nullable=True),
    sa.Column('resolution_pct', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ethics_grievances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ethics_grievances_reporting_period_id'), ['reporting_period_id'], unique=False)

    op.create_table('procurement_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reporting_period_id', sa.String(), nullable=False),
    sa.Column('total_procurement_spend_cr', sa.Float(), nullable=False),
    sa.Column('msme_spend_cr', sa.Float(), nullable=False),
    sa.Column('msme_spend_pct', sa.Float(), nullable=False),
    sa.Column('local_sourcing_pct', sa.Float(), nullable=False),
    sa.Column('suppliers_audited_count', sa.Integer(), nullable=True),
    sa.Column('total_active_suppliers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_metrics_reporting_period_id'), ['reporting_period_id'], unique=False)

    op.create_table('csr_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subsidiary_id', sa.String(), nullable=True),
    sa.Column('business_unit_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('responsible_owner', sa.String(), nullable=True),
    sa.Column('partner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reporting_period_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['csr_program_categories.id'], ),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_table('communities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('responsible_person', sa.String(), nullable=True),
    sa.Column('target_population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_budget_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('approved_budget', sa.Float(), nullable=False),
    sa.Column('actual_spend', sa.Float(), nullable=False),
    sa.Column('committed', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('remaining', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_project_milestones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_date', sa.String(), nullable=False),
    sa.Column('achieved_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_spend_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.String(), nullable=False),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_impact_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('measurement_date', sa.String(), nullable=True),
    sa.Column('reporting_period_id', sa.String(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_documents.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['social_impact_indicators.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiary_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('beneficiary_group_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_group_id'], ['beneficiary_groups.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_grievances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grievance_number', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grievance_number')
    )
    op.create_table('community_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csr_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakeholder_engagements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('stakeholder_id', sa.String(), nullable=True),
    sa.Column('stakeholder_type', sa.String(), nullable=True),
    sa.Column('stakeholder_group', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('issues_raised', sa.Text(), nullable=True),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['csr_projects.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grievance_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grievance_id', sa.String(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['community_grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grievance_actions')
    op.drop_table('stakeholder_engagements')
    op.drop_table('csr_activities')
    op.drop_table('community_locations')
    op.drop_table('community_grievances')
    op.drop_table('beneficiary_records')
    op.drop_table('social_impact_records')
    op.drop_table('csr_spend_records')
    op.drop_table('csr_project_milestones')
    op.drop_table('csr_budget_records')
    op.drop_table('csr_actions')
    op.drop_table('communities')
    op.drop_table('csr_projects')
    with op.batch_alter_table('procurement_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_metrics_reporting_period_id'))

    op.drop_table('procurement_metrics')
    with op.batch_alter_table('ethics_grievances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ethics_grievances_reporting_period_id'))

    op.drop_table('ethics_grievances')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_vendor_code'))

    op.drop_table('suppliers')
    op.drop_table('stakeholders')
    op.drop_table('social_impact_indicators')
    with op.batch_alter_table('governance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_policies_policy_code'))

    op.drop_table('governance_policies')
    op.drop_table('csr_program_categories')
    op.drop_table('csr_notifications')
    op.drop_table('beneficiary_groups')
    # ### end Alembic commands ###
