"""add_brsr_principles_answers_and_sources

Revision ID: b28d21a8f0de
Revises: 7db6414754c1
Create Date: 2026-10-05 23:57:14.616871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28d21a8f0de'
down_revision: Union[str, None] = '7db6414754c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brsr_principles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('framework_id', sa.String(), nullable=False),
    sa.Column('principle_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['brsr_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brsr_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('framework_id', sa.String(), nullable=False),
    sa.Column('reporting_period_id', sa.String(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['brsr_frameworks.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['brsr_indicators.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brsr_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brsr_answers_framework_id'), ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brsr_answers_indicator_id'), ['indicator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brsr_answers_reporting_period_id'), ['reporting_period_id'], unique=False)

    op.create_table('brsr_answer_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('source_record_type', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('calculation_result_id', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('trace_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['brsr_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brsr_answer_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brsr_answer_sources_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brsr_answer_sources_source_record_id'), ['source_record_id'], unique=False)

    with op.batch_alter_table('brsr_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_brsr_indicators_indicator_code'), ['indicator_code'], unique=True)

    with op.batch_alter_table('brsr_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric_key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('evidence_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('formula_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brsr_mappings', schema=None) as batch_op:
        batch_op.drop_column('formula_code')
        batch_op.drop_column('evidence_required')
        batch_op.drop_column('metric_key')

    with op.batch_alter_table('brsr_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brsr_indicators_indicator_code'))
        batch_op.drop_column('required')

    with op.batch_alter_table('brsr_answer_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brsr_answer_sources_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_brsr_answer_sources_answer_id'))

    op.drop_table('brsr_answer_sources')
    with op.batch_alter_table('brsr_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brsr_answers_reporting_period_id'))
        batch_op.drop_index(batch_op.f('ix_brsr_answers_indicator_id'))
        batch_op.drop_index(batch_op.f('ix_brsr_answers_framework_id'))

    op.drop_table('brsr_answers')
    op.drop_table('brsr_principles')
    # ### end Alembic commands ###
