"""add_calculation_and_validation_engines_and_units

Revision ID: e05ed49c7e7f
Revises: f6fad23d0908
Create Date: 2026-10-05 22:27:09.098712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05ed49c7e7f'
down_revision: Union[str, None] = 'f6fad23d0908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('validation_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=True),
    sa.Column('condition_expression', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=True),
    sa.Column('message_template', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_rules_rule_code'), ['rule_code'], unique=True)

    op.create_table('calculation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_runs_submission_id'), ['submission_id'], unique=False)

    op.create_table('validation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rules_evaluated_count', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_runs_submission_id'), ['submission_id'], unique=False)

    op.create_table('calculation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calculation_run_id', sa.String(), nullable=False),
    sa.Column('source_record_type', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('input_value', sa.Float(), nullable=False),
    sa.Column('input_unit', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('normalized_unit', sa.String(), nullable=True),
    sa.Column('factor_id', sa.String(), nullable=True),
    sa.Column('factor_version', sa.String(), nullable=True),
    sa.Column('formula_code', sa.String(), nullable=False),
    sa.Column('result_value', sa.Float(), nullable=False),
    sa.Column('result_unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_results_calculation_run_id'), ['calculation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calculation_results_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('validation_run_id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source_record_type', sa.String(), nullable=True),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_validation_run_id'), ['validation_run_id'], unique=False)

    with op.batch_alter_table('emission_factors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    with op.batch_alter_table('unit_conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_conversions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('source')
        batch_op.drop_column('version')
        batch_op.drop_column('formula_code')

    with op.batch_alter_table('emission_factors', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_results_validation_run_id'))

    op.drop_table('validation_results')
    with op.batch_alter_table('calculation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_results_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_calculation_results_calculation_run_id'))

    op.drop_table('calculation_results')
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_runs_submission_id'))

    op.drop_table('validation_runs')
    with op.batch_alter_table('calculation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_runs_submission_id'))

    op.drop_table('calculation_runs')
    with op.batch_alter_table('validation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_rules_rule_code'))

    op.drop_table('validation_rules')
    op.drop_table('units')
    op.drop_table('factor_sources')
    # ### end Alembic commands ###
