"""add_evidence_lifecycle_and_links

Revision ID: f6fad23d0908
Revises: 6e9603f7cfca
Create Date: 2026-10-05 22:19:09.418610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fad23d0908'
down_revision: Union[str, None] = '6e9603f7cfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('source_record_type', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('brsr_indicator_id', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(), nullable=False, server_default='Energy'))
        batch_op.add_column(sa.Column('related_record', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='Pending'))
        batch_op.add_column(sa.Column('version', sa.String(), nullable=False, server_default='v1.0'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('reporting_period_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('sha256_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.alter_column('sha256_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('reporting_period_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('version')
        batch_op.drop_column('status')
        batch_op.drop_column('uploaded_by_name')
        batch_op.drop_column('related_record')
        batch_op.drop_column('module')

    op.drop_table('evidence_links')
    op.drop_table('evidence_history')
    # ### end Alembic commands ###
