// Master Data for Governance & Compliance Module (MEIL ESG & BRSR Platform)
// Exact alignment with Master Reference Design (16 Screens)

export const INITIAL_POLICIES = [
  {
    id: 'POL-001',
    code: 'POL-001',
    name: 'Code of Conduct',
    category: 'Governance',
    department: 'Legal & Ethics',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    effectiveDate: '01 Jan 2024',
    reviewDate: '01 Jan 2026',
    version: 'v3.0',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 3,
    scope: 'Group Level & Subsidiaries',
    description: 'Mandatory standard of conduct and professional ethics for all directors, senior management, and workforce.',
    applicability: 'All Employees & Business Partners'
  },
  {
    id: 'POL-002',
    code: 'POL-002',
    name: 'Anti-Corruption Policy',
    category: 'Ethics & Integrity',
    department: 'Compliance',
    owner: 'Compliance',
    ownerName: 'Adv. S. K. Nair',
    effectiveDate: '15 Feb 2024',
    reviewDate: '15 Feb 2026',
    version: 'v2.1',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 4,
    scope: 'All Subsidiaries & Business Units',
    description: 'Zero-tolerance policy on bribery, corrupt practices, facilitation payments, and kickbacks in accordance with Prevention of Corruption Act.',
    applicability: '100% Workforce & Third Parties',
    documentUrl: '/docs/POL-002-Anti-Corruption-v2.1.pdf',
    relatedObligations: ['CO-003', 'CO-001'],
    relatedControls: ['CTR-001', 'CTR-006']
  },
  {
    id: 'POL-003',
    code: 'POL-003',
    name: 'Whistleblower Policy',
    category: 'Ethics & Integrity',
    department: 'Compliance',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    effectiveDate: '10 Mar 2024',
    reviewDate: '10 Mar 2026',
    version: 'v1.4',
    status: 'Under Review',
    approvalStatus: 'Pending Committee',
    evidenceCount: 2,
    scope: 'Group Level',
    description: 'Secure, retaliation-free speak-up channel for reporting unethical behavior, malpractice, fraud, or violations of law.',
    applicability: 'All Stakeholders & Whistleblowers'
  },
  {
    id: 'POL-004',
    code: 'POL-004',
    name: 'Human Rights Policy',
    category: 'Social',
    department: 'HR',
    owner: 'HR',
    ownerName: 'Sunita Raman',
    effectiveDate: '01 Apr 2024',
    reviewDate: '01 Apr 2026',
    version: 'v2.0',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 3,
    scope: 'All Project Sites & Plants',
    description: 'Commitment to uphold human rights, prohibiting child labour, forced labour, discrimination, and safeguarding worker dignity.',
    applicability: 'All Workforce, Contractors & Supply Chain'
  },
  {
    id: 'POL-005',
    code: 'POL-005',
    name: 'Data Privacy Policy',
    category: 'Governance',
    department: 'IT & Security',
    owner: 'IT',
    ownerName: 'Amit Shah',
    effectiveDate: '12 May 2024',
    reviewDate: '12 May 2026',
    version: 'v1.2',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 2,
    scope: 'Digital Platforms & Enterprise Systems',
    description: 'Compliance with India Digital Personal Data Protection Act (DPDPA 2023) ensuring consent, data security, and confidentiality.',
    applicability: 'Enterprise Data Architecture'
  },
  {
    id: 'POL-006',
    code: 'POL-006',
    name: 'Related Party Transactions',
    category: 'Governance',
    department: 'Finance',
    owner: 'Finance',
    ownerName: 'Vikram Joshi',
    effectiveDate: '20 Jun 2024',
    reviewDate: '20 Jun 2026',
    version: 'v2.3',
    status: 'Due for Review',
    approvalStatus: 'Review Due',
    evidenceCount: 5,
    scope: 'Board Level & Joint Ventures',
    description: 'Framework to regulate transactions between MEIL and related parties adhering to Companies Act and SEBI LODR Regulations.',
    applicability: 'Directors, KMP & Subsidiaries'
  },
  {
    id: 'POL-007',
    code: 'POL-007',
    name: 'Environmental Policy',
    category: 'Environmental',
    department: 'ESG',
    owner: 'ESG',
    ownerName: 'Rajeshwar K.',
    effectiveDate: '01 Jul 2024',
    reviewDate: '01 Jul 2026',
    version: 'v3.1',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 6,
    scope: 'All Engineering & Construction Projects',
    description: 'Comprehensive environmental stewardship policy covering emissions, resource conservation, biodiversity, and circularity.',
    applicability: 'All Operational Facilities'
  },
  {
    id: 'POL-008',
    code: 'POL-008',
    name: 'Health & Safety Policy',
    category: 'Social',
    department: 'HSE',
    owner: 'HSE',
    ownerName: 'Rajeshwar K.',
    effectiveDate: '15 Aug 2024',
    reviewDate: '15 Aug 2026',
    version: 'v4.0',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 8,
    scope: 'All Construction Sites & Plants',
    description: 'Vision Zero safety charter, hazard identification, mandatory PPE, and continuous incident prevention protocols.',
    applicability: 'Employees, Subcontractors, Visitors'
  },
  {
    id: 'POL-009',
    code: 'POL-009',
    name: 'Sustainable Procurement Policy',
    category: 'Governance',
    department: 'Procurement',
    owner: 'Procurement',
    ownerName: 'Anand Mahindra V.',
    effectiveDate: '01 Sep 2024',
    reviewDate: '01 Sep 2026',
    version: 'v1.1',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 3,
    scope: 'Supply Chain Tier 1 & 2',
    description: 'ESG criteria evaluation, MSME inclusion, and local sourcing priority in all vendor onboarding contracts.',
    applicability: 'All Approved Suppliers'
  },
  {
    id: 'POL-010',
    code: 'POL-010',
    name: 'CSR & Community Engagement Policy',
    category: 'Social',
    department: 'CSR',
    owner: 'CSR',
    ownerName: 'Priya Nair',
    effectiveDate: '15 Sep 2024',
    reviewDate: '15 Sep 2026',
    version: 'v2.0',
    status: 'Active',
    approvalStatus: 'Approved',
    evidenceCount: 4,
    scope: 'MEIL Foundation & Impact Zones',
    description: '2% statutory CSR expenditure compliance, Schedule VII aligned community welfare initiatives and monitoring.',
    applicability: 'Community Programs & Beneficiaries'
  }
];

export const INITIAL_OBLIGATIONS = [
  {
    id: 'CO-001',
    code: 'CO-001',
    requirement: 'Annual Board Report',
    category: 'Legal',
    source: 'Companies Act',
    owner: 'Compl.',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '30 Sep 2026',
    status: 'Compliant',
    evidence: 'Verified',
    applicability: 'Applicable',
    frequency: 'Yearly',
    scope: 'MEIL Group HQ',
    lastReview: '12 Sep 2026',
    description: 'Filing of Annual Board Report with Directors Responsibility Statement under Section 134.'
  },
  {
    id: 'CO-002',
    code: 'CO-002',
    requirement: 'ESG/BRSR Disclosure',
    category: 'ESG',
    source: 'SEBI',
    owner: 'Compliance',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '15 Nov 2026',
    status: 'In Progress',
    evidence: 'In Review',
    applicability: 'Applicable',
    frequency: 'Annual',
    scope: 'Top 1000 Listed Entities Group Scope',
    lastReview: '08 Sep 2026',
    description: 'Mandatory Business Responsibility and Sustainability Reporting across NGRBC Principles 1-9.'
  },
  {
    id: 'CO-003',
    code: 'CO-003',
    requirement: 'Anti-Bribery Compliance',
    category: 'Legal',
    source: 'Prevention of Corruption Act',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '31 Dec 2026',
    status: 'Overdue',
    evidence: 'Missing Evidence',
    applicability: 'Applicable',
    frequency: 'Quarterly',
    scope: 'All Procurement & Third-Party Tenders',
    lastReview: '15 Aug 2026',
    description: 'Mandatory third-party integrity screening and vendor anti-corruption declarations.'
  },
  {
    id: 'CO-004',
    code: 'CO-004',
    requirement: 'Data Privacy Compliance',
    category: 'Governance',
    source: 'DPDP Act 2023',
    owner: 'IT',
    ownerName: 'Amit Shah',
    dueDate: '30 Oct 2026',
    status: 'In Progress',
    evidence: 'Partial',
    applicability: 'Applicable',
    frequency: 'Half-Yearly',
    scope: 'Digital HR, Vendor & Customer Data',
    lastReview: '02 Sep 2026',
    description: 'Data Protection Officer (DPO) audits and consent management system enforcement.'
  },
  {
    id: 'CO-005',
    code: 'CO-005',
    requirement: 'Labour Law Compliance',
    category: 'Social',
    source: 'Labour Act',
    owner: 'HR',
    ownerName: 'Sunita Raman',
    dueDate: '31 Dec 2026',
    status: 'Compliant',
    evidence: 'Verified',
    applicability: 'Applicable',
    frequency: 'Monthly',
    scope: 'All 258+ Project Sites',
    lastReview: '10 Sep 2026',
    description: 'Statutory returns under EPF, ESIC, CLRA, BOCW and Minimum Wages Acts.'
  },
  {
    id: 'CO-006',
    code: 'CO-006',
    requirement: 'Environmental Clearance',
    category: 'Environmental',
    source: 'EC Act',
    owner: 'ESG',
    ownerName: 'Rajeshwar K.',
    dueDate: '30 Sep 2026',
    status: 'Pending Review',
    evidence: 'Pending Review',
    applicability: 'Applicable',
    frequency: 'Half-Yearly',
    scope: 'Zojila, Polavaram & Green Energy Sites',
    lastReview: '04 Sep 2026',
    description: 'Compliance reports to MoEFCC regional offices for environmental clearances (EC/CTO).'
  },
  {
    id: 'CO-007',
    code: 'CO-007',
    requirement: 'Related Party Disclosure',
    category: 'Legal',
    source: 'SEBI LODR',
    owner: 'Finance',
    ownerName: 'Vikram Joshi',
    dueDate: '15 Nov 2026',
    status: 'Compliant',
    evidence: 'Verified',
    applicability: 'Applicable',
    frequency: 'Half-Yearly',
    scope: 'Subsidiaries & Joint Ventures',
    lastReview: '28 Aug 2026',
    description: 'Half-yearly disclosures of related party transactions in XBRL format.'
  },
  {
    id: 'CO-008',
    code: 'CO-008',
    requirement: 'Risk Management Review',
    category: 'Governance',
    source: 'Internal Policy',
    owner: 'Risk',
    ownerName: 'Rahul Mehta',
    dueDate: '31 Dec 2026',
    status: 'Due Soon',
    evidence: 'Draft',
    applicability: 'Applicable',
    frequency: 'Quarterly',
    scope: 'Enterprise Risk Management Committee',
    lastReview: '01 Sep 2026',
    description: 'Quarterly review of top strategic, operational, financial, and climate risks.'
  }
];

export const INITIAL_CONTROLS = [
  {
    id: 'CTR-001',
    code: 'CTR-001',
    name: 'Vendor Due Diligence',
    type: 'Preventive',
    obligation: 'CO-003',
    owner: 'Procurement',
    ownerName: 'Anand Mahindra V.',
    lastTest: '10 Sep 2026',
    result: 'Pass',
    status: 'Active',
    frequency: 'Per Vendor Onboarding',
    testMethod: 'Automated Sanction & AML Screening',
    evidenceRequired: 'Vendor Due Diligence Certificate'
  },
  {
    id: 'CTR-002',
    code: 'CTR-002',
    name: 'Approval Workflow',
    type: 'Detective',
    obligation: 'CO-001',
    owner: 'Finance',
    ownerName: 'Vikram Joshi',
    lastTest: '12 Sep 2026',
    result: 'Pass',
    status: 'Active',
    frequency: 'Continuous',
    testMethod: 'ERP Multi-Tier Approval Log Inspection',
    evidenceRequired: 'Delegation of Authority (DoA) Audit Log'
  },
  {
    id: 'CTR-003',
    code: 'CTR-003',
    name: 'Access Control',
    type: 'IT Automated',
    obligation: 'CO-004',
    owner: 'IT',
    ownerName: 'Amit Shah',
    lastTest: '05 Sep 2026',
    result: 'Fail',
    status: 'Needs Action',
    frequency: 'Monthly',
    testMethod: 'Privileged Access Review & Ghost Account Scan',
    evidenceRequired: 'IAM Quarterly Access Recertification'
  },
  {
    id: 'CTR-004',
    code: 'CTR-004',
    name: 'HSE Compliance Review',
    type: 'Preventive',
    obligation: 'CO-006',
    owner: 'ESG',
    ownerName: 'Rajeshwar K.',
    lastTest: '08 Sep 2026',
    result: 'Pass',
    status: 'Active',
    frequency: 'Bi-Monthly',
    testMethod: 'Site Inspection Checklist & Emission Logs',
    evidenceRequired: 'Consent to Operate (CTO) Records'
  },
  {
    id: 'CTR-005',
    code: 'CTR-005',
    name: 'Related Party Monitoring',
    type: 'Detective',
    obligation: 'CO-007',
    owner: 'Finance',
    ownerName: 'Vikram Joshi',
    lastTest: '15 Aug 2026',
    result: 'Partial',
    status: 'Under Review',
    frequency: 'Quarterly',
    testMethod: 'Intercompany Ledger Reconciliations',
    evidenceRequired: 'Audit Committee Approval Minutes'
  },
  {
    id: 'CTR-006',
    code: 'CTR-006',
    name: 'Whistleblower Monitoring',
    type: 'Detective',
    obligation: 'CO-003',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    lastTest: '01 Sep 2026',
    result: 'Pass',
    status: 'Active',
    frequency: 'Monthly',
    testMethod: 'Independent Ethics Hotline Audit',
    evidenceRequired: 'Monthly Ombudsperson Registry Log'
  }
];

export const INITIAL_ASSESSMENTS = [
  {
    id: 'AS-001',
    code: 'AS-001',
    scope: 'Group Level',
    category: 'Governance',
    assessor: 'Internal Audit',
    date: '12 Aug 2026',
    status: 'Completed',
    findings: 0,
    coverage: '100%',
    nextReview: '12 Feb 2027'
  },
  {
    id: 'AS-002',
    code: 'AS-002',
    scope: 'Finance',
    category: 'Compliance',
    assessor: 'External Audit',
    date: '18 Aug 2026',
    status: 'In Progress',
    findings: 2,
    coverage: '85%',
    nextReview: '18 Oct 2026'
  },
  {
    id: 'AS-003',
    code: 'AS-003',
    scope: 'HSE Compliance',
    category: 'ESG',
    assessor: 'ESG Team',
    date: '22 Aug 2026',
    status: 'Completed',
    findings: 1,
    coverage: '95%',
    nextReview: '22 Nov 2026'
  },
  {
    id: 'AS-004',
    code: 'AS-004',
    scope: 'IT & Data Privacy',
    category: 'Audit',
    assessor: 'IT Audit',
    date: '29 Aug 2026',
    status: 'Under Review',
    findings: 3,
    coverage: '78%',
    nextReview: '29 Sep 2026'
  },
  {
    id: 'AS-005',
    code: 'AS-005',
    scope: 'Procurement',
    category: 'Ethics',
    assessor: 'Ethics Team',
    date: '02 Sep 2026',
    status: 'Planned',
    findings: 0,
    coverage: '0%',
    nextReview: '15 Oct 2026'
  },
  {
    id: 'AS-006',
    code: 'AS-006',
    scope: 'CSR Governance',
    category: 'CSR',
    assessor: 'External Audit',
    date: '06 Sep 2026',
    status: 'Completed',
    findings: 2,
    coverage: '92%',
    nextReview: '06 Mar 2027'
  }
];

export const INITIAL_ETHICS_CASES = [
  {
    id: 'ETH-001',
    code: 'ETH-001',
    category: 'Whistleblower',
    date: '05 Sep 2026',
    severity: 'High',
    owner: 'Compliance',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '10 Oct 2026',
    status: 'Under Review',
    scope: 'North Regional Office',
    description: 'Anonymous report regarding subcontractor overtime record discrepancies.',
    resolution: 'Triage complete; independent fact-finding committee convened.'
  },
  {
    id: 'ETH-002',
    code: 'ETH-002',
    category: 'Conflict of Interest',
    date: '08 Sep 2026',
    severity: 'Medium',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '25 Sep 2026',
    status: 'Investigation',
    scope: 'Procurement Unit 3',
    description: 'Vendor declaration flag regarding familial relationship with procurement evaluator.',
    resolution: 'Evaluator recused; secondary vendor bid evaluation initiated.'
  },
  {
    id: 'ETH-003',
    code: 'ETH-003',
    category: 'Fraud',
    date: '10 Sep 2026',
    severity: 'Critical',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '15 Sep 2026',
    status: 'Action Required',
    scope: 'Main Warehouse Hyderabad',
    description: 'Suspected scrap metal inventory reconciliation anomaly flagged by digital weighbridge.',
    resolution: 'Immediate gate audit conducted; physical verification underway.'
  },
  {
    id: 'ETH-004',
    code: 'ETH-004',
    category: 'Misconduct',
    date: '11 Sep 2026',
    severity: 'Medium',
    owner: 'HR',
    ownerName: 'Sunita Raman',
    dueDate: '30 Sep 2026',
    status: 'Under Review',
    scope: 'Site Office - Polavaram',
    description: 'Verbal altercation and breach of respectful workplace guidelines.',
    resolution: 'Internal Complaints Committee review scheduled.'
  },
  {
    id: 'ETH-005',
    code: 'ETH-005',
    category: 'Policy Violation',
    date: '13 Sep 2026',
    severity: 'Low',
    owner: 'Compliance',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '20 Sep 2026',
    status: 'Resolved',
    scope: 'Digital Services',
    description: 'Unauthorized USB device usage on engineering workstation.',
    resolution: 'Security warning issued; device quarantined and scanned.'
  }
];

export const INITIAL_GRIEVANCES = [
  {
    id: 'GRV-001',
    code: 'GRV-001',
    type: 'Community',
    project: 'Zojila Tunnel',
    date: '02 Sep 2026',
    severity: 'High',
    status: 'Open',
    owner: 'CSR Lead',
    dueDate: '16 Sep 2026',
    description: 'Dust suppression concerns raised by village elders near northern portal access road.',
    resolution: 'Deployment of additional water sprinklers and speed governors on tippers.'
  },
  {
    id: 'GRV-002',
    code: 'GRV-002',
    type: 'HR Related',
    project: 'City Office',
    date: '05 Sep 2026',
    severity: 'Medium',
    status: 'Under Review',
    owner: 'HR Team',
    dueDate: '20 Sep 2026',
    description: 'Grievance regarding transport bus timing changes for late shift staff.',
    resolution: 'Route optimization plan under review by admin.'
  },
  {
    id: 'GRV-003',
    code: 'GRV-003',
    type: 'Vendor',
    project: 'Procurement',
    date: '08 Sep 2026',
    severity: 'Low',
    status: 'Investigation',
    owner: 'Supply Chain',
    dueDate: '22 Sep 2026',
    description: 'Invoice payment clearance query for cement consignment batch #781.',
    resolution: 'Finance QA clearance pending test certificate validation.'
  },
  {
    id: 'GRV-004',
    code: 'GRV-004',
    type: 'Environmental',
    project: 'Access Road',
    date: '10 Sep 2026',
    severity: 'High',
    status: 'Resolved',
    owner: 'EHS Team',
    dueDate: '12 Sep 2026',
    description: 'Drainage blockage during heavy rainfall affecting adjacent agricultural field.',
    resolution: 'Culvert cleared and reinforced within 24 hours; field verified with sarpanch.'
  },
  {
    id: 'GRV-005',
    code: 'GRV-005',
    type: 'Safety',
    project: 'Main Plant',
    date: '12 Sep 2026',
    severity: 'Low',
    status: 'Resolved',
    owner: 'HSE Lead',
    dueDate: '14 Sep 2026',
    description: 'Damaged guard rail near cooling tower access catwalk.',
    resolution: 'Repaired and certified by structural safety officer.'
  }
];

export const INITIAL_ACTIONS = [
  {
    id: 'CA-001',
    code: 'CA-001',
    source: 'Assessment',
    issue: 'Data privacy gap',
    priority: 'High',
    owner: 'IT',
    ownerName: 'Amit Shah',
    dueDate: '15 Sep 2026',
    status: 'In Progress',
    evidence: 'In Progress',
    verification: 'Pending DPO Verification'
  },
  {
    id: 'CA-002',
    code: 'CA-002',
    source: 'Control Test',
    issue: 'Access control failure',
    priority: 'Critical',
    owner: 'IT',
    ownerName: 'Amit Shah',
    dueDate: '18 Sep 2026',
    status: 'Overdue',
    evidence: 'Required',
    verification: 'Revoke terminated IDs'
  },
  {
    id: 'CA-003',
    code: 'CA-003',
    source: 'Ethics Case',
    issue: 'Investigation update',
    priority: 'Medium',
    owner: 'Legal',
    ownerName: 'Adv. S. K. Nair',
    dueDate: '20 Sep 2026',
    status: 'Open',
    evidence: 'Draft',
    verification: 'Committee Report'
  },
  {
    id: 'CA-004',
    code: 'CA-004',
    source: 'Grievance',
    issue: 'Community concern',
    priority: 'High',
    owner: 'CSR',
    ownerName: 'Priya Nair',
    dueDate: '22 Sep 2026',
    status: 'In Progress',
    evidence: 'Site Photos',
    verification: 'Community Signoff'
  },
  {
    id: 'CA-005',
    code: 'CA-005',
    source: 'Obligation',
    issue: 'Missing evidence',
    priority: 'Medium',
    owner: 'Finance',
    ownerName: 'Vikram Joshi',
    dueDate: '25 Sep 2026',
    status: 'Open',
    evidence: 'Bank Statement',
    verification: 'Treasury Audit'
  }
];

export const INITIAL_DISCLOSURES = [
  {
    id: 'DSC-001',
    code: 'DSC-001',
    type: 'Board Meeting Record',
    scope: 'Board',
    period: 'FY 2026-27',
    owner: 'Company',
    ownerName: 'Company Secretary',
    status: 'Compliance',
    approval: 'Completed',
    evidence: 'Verified',
    recordsCount: 4
  },
  {
    id: 'DSC-002',
    code: 'DSC-002',
    type: 'Related Party Disclosure',
    scope: 'Group',
    period: 'FY 2026-27',
    owner: 'Finance',
    ownerName: 'Vikram Joshi',
    status: 'Disclosures',
    approval: 'Under Review',
    evidence: 'Pending Review',
    recordsCount: 12
  },
  {
    id: 'DSC-003',
    code: 'DSC-003',
    type: 'Governance',
    scope: 'Group',
    period: 'FY 2026-27',
    owner: 'Compliance',
    ownerName: 'Adv. S. K. Nair',
    status: 'Draft',
    approval: 'Draft',
    evidence: 'Draft',
    recordsCount: 6
  },
  {
    id: 'DSC-004',
    code: 'DSC-004',
    type: 'ESG/BRSR Governance',
    scope: 'Group',
    period: 'FY 2026-27',
    owner: 'ESG',
    ownerName: 'Rajeshwar K.',
    status: 'Compliant',
    approval: 'In Progress',
    evidence: 'Verified',
    recordsCount: 9
  },
  {
    id: 'DSC-005',
    code: 'DSC-005',
    type: 'Ethics Program Report',
    scope: 'Group',
    period: 'FY 2026-27',
    owner: 'Compliance',
    ownerName: 'Adv. S. K. Nair',
    status: 'File',
    approval: 'Approved',
    evidence: 'Verified',
    recordsCount: 5
  }
];

export const INITIAL_EVIDENCE_ITEMS = [
  {
    id: 'EV-001',
    code: 'EV-001',
    title: 'Policy Document',
    linkedTo: 'POL-002',
    type: 'PDF',
    size: '2.4 MB',
    uploadedDate: '10 Sep 2026',
    status: 'Verified',
    uploadedBy: 'Adv. S. K. Nair'
  },
  {
    id: 'EV-002',
    code: 'EV-002',
    title: 'Control Test Report',
    linkedTo: 'CTR-003',
    type: 'PDF',
    size: '1.8 MB',
    uploadedDate: '12 Sep 2026',
    status: 'Pending Review',
    uploadedBy: 'Amit Shah'
  },
  {
    id: 'EV-003',
    code: 'EV-003',
    title: 'Assessment Evidence',
    linkedTo: 'AS-004',
    type: 'PDF',
    size: '3.1 MB',
    uploadedDate: '14 Sep 2026',
    status: 'Verified',
    uploadedBy: 'IT Audit'
  },
  {
    id: 'EV-004',
    code: 'EV-004',
    title: 'Grievance Document',
    linkedTo: 'GRV-001',
    type: 'Image',
    size: '4.2 MB',
    uploadedDate: '15 Sep 2026',
    status: 'In Review',
    uploadedBy: 'Priya Nair'
  },
  {
    id: 'EV-005',
    code: 'EV-005',
    title: 'Disclosure File',
    linkedTo: 'DSC-001',
    type: 'PDF',
    size: '1.2 MB',
    uploadedDate: '16 Sep 2026',
    status: 'Under Review',
    uploadedBy: 'Company Secretary'
  }
];

export const INITIAL_SUBMISSIONS = [
  {
    id: 'SUB-001',
    code: 'SUB-001',
    module: 'Policies',
    scope: 'Group',
    period: 'FY 2026-27',
    status: 'Approved',
    submittedBy: 'Adv. S. K. Nair',
    reviewer: 'Rohit Kumar',
    lastUpdated: '10 Sep 2026'
  },
  {
    id: 'SUB-002',
    code: 'SUB-002',
    module: 'Compliance',
    scope: 'Group',
    period: 'FY 2026-27',
    status: 'Under Review',
    submittedBy: 'Adv. S. K. Nair',
    reviewer: 'Auditor General',
    lastUpdated: '12 Sep 2026'
  },
  {
    id: 'SUB-003',
    code: 'SUB-003',
    module: 'Ethics',
    scope: 'BU-1',
    period: 'FY 2026-27',
    status: 'Correction Required',
    submittedBy: 'BU-1 Lead',
    reviewer: 'Adv. S. K. Nair',
    lastUpdated: '14 Sep 2026'
  },
  {
    id: 'SUB-004',
    code: 'SUB-004',
    module: 'Disclosures',
    scope: 'Group',
    period: 'FY 2026-27',
    status: 'Approved',
    submittedBy: 'Company Sec.',
    reviewer: 'Board Chair',
    lastUpdated: '15 Sep 2026'
  },
  {
    id: 'SUB-005',
    code: 'SUB-005',
    module: 'BRSR Mapping',
    scope: 'Group',
    period: 'FY 2026-27',
    status: 'Under Review',
    submittedBy: 'ESG Lead',
    reviewer: 'Audit Committee',
    lastUpdated: '16 Sep 2026'
  }
];

export const INITIAL_ACTION_CENTER_TASKS = [
  {
    id: 'ACT-001',
    task: 'Control test failed',
    source: 'CTR-003',
    owner: 'IT',
    dueDate: '10 Sep 2026',
    priority: 'Critical',
    status: 'Overdue',
    actionLabel: 'Start',
    targetScreen: 'controls'
  },
  {
    id: 'ACT-002',
    task: 'Policy review due',
    source: 'POL-006',
    owner: 'Finance',
    dueDate: '12 Sep 2026',
    priority: 'High',
    status: 'Due Today',
    actionLabel: 'View',
    targetScreen: 'policy-detail'
  },
  {
    id: 'ACT-003',
    task: 'Evidence missing',
    source: 'AS-004',
    owner: 'ESG',
    dueDate: '15 Sep 2026',
    priority: 'Medium',
    status: 'Due Soon',
    actionLabel: 'Upload',
    targetScreen: 'evidence'
  },
  {
    id: 'ACT-004',
    task: 'Grievance follow-up',
    source: 'GRV-001',
    owner: 'Legal',
    dueDate: '16 Sep 2026',
    priority: 'High',
    status: 'In Progress',
    actionLabel: 'Resolve',
    targetScreen: 'grievances'
  },
  {
    id: 'ACT-005',
    task: 'Submission correction',
    source: 'SUB-003',
    owner: 'Compliance',
    dueDate: '18 Sep 2026',
    priority: 'Critical',
    status: 'Action Required',
    actionLabel: 'Review',
    targetScreen: 'submissions'
  }
];

export const INITIAL_BRSR_MAPPINGS = [
  {
    id: 'BRSR-001',
    indicator: 'C.1.1: Board Composition',
    sourceRecords: 'DSC-001',
    dataAvailability: 'Available',
    evidence: 'Verified',
    status: 'Complete',
    readiness: 'Ready'
  },
  {
    id: 'BRSR-002',
    indicator: 'C.1.2: Ethics Policy',
    sourceRecords: 'POL-001',
    dataAvailability: 'Available',
    evidence: 'Verified',
    status: 'Complete',
    readiness: 'Ready'
  },
  {
    id: 'BRSR-003',
    indicator: 'C.1.3: Anti-Corruption',
    sourceRecords: 'CO-003, CTR-001',
    dataAvailability: 'Partial',
    evidence: 'Pending',
    status: 'Under Review',
    readiness: 'In Progress'
  },
  {
    id: 'BRSR-004',
    indicator: 'C.1.4: Grievance Redressal',
    sourceRecords: 'GRV-001, POL-003',
    dataAvailability: 'Available',
    evidence: 'Verified',
    status: 'Complete',
    readiness: 'Ready'
  },
  {
    id: 'BRSR-005',
    indicator: 'C.1.5: Stakeholder Engagement',
    sourceRecords: 'AS-006, DSC-004',
    dataAvailability: 'Available',
    evidence: 'In Review',
    status: 'Under Review',
    readiness: 'In Progress'
  }
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'AUD-001',
    dateTime: '12 Sep 2026 15:30',
    user: 'Priya Nair',
    action: 'Policy Updated',
    entity: 'Policy',
    entityId: 'POL-002',
    details: 'Version 2.0 created'
  },
  {
    id: 'AUD-002',
    dateTime: '12 Sep 2026 16:45',
    user: 'Amit Shah',
    action: 'Control Test Failed',
    entity: 'Control',
    entityId: 'CTR-003',
    details: 'Result: Fail'
  },
  {
    id: 'AUD-003',
    dateTime: '13 Sep 2026 10:15',
    user: 'Adv. S. K. Nair',
    action: 'Action Created',
    entity: 'Action',
    entityId: 'CA-002',
    details: 'Access control issue'
  },
  {
    id: 'AUD-004',
    dateTime: '14 Sep 2026 11:20',
    user: 'Rohit Kumar',
    action: 'Evidence Uploaded',
    entity: 'Evidence',
    entityId: 'EV-002',
    details: 'PDF document'
  },
  {
    id: 'AUD-005',
    dateTime: '15 Sep 2026 14:10',
    user: 'Rahul Mehta',
    action: 'Submission Approved',
    entity: 'Submission',
    entityId: 'SUB-001',
    details: 'Approved by HQ'
  }
];
