import { jsPDF } from 'jspdf';

/**
 * Universal PDF Generator for MEIL ESG & BRSR Platform
 * Produces real, valid, beautifully styled PDF documents.
 */

// Helper to draw MEIL corporate header
function drawMeilHeader(doc, title, subtitle) {
  // Top primary bar
  doc.setFillColor(15, 23, 42); // Navy #0F172A
  doc.rect(0, 0, 210, 24, 'F');

  // Red accent line
  doc.setFillColor(220, 38, 38); // MEIL Red #DC2626
  doc.rect(0, 24, 210, 2.5, 'F');

  // MEIL Logo Icon Box
  doc.setFillColor(220, 38, 38);
  doc.roundedRect(14, 5, 14, 14, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('M', 18.5, 15);

  // Corporate Brand Text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text('MEIL ESG & BRSR STATUTORY PORTAL', 34, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(203, 213, 225);
  doc.text('Megha Engineering & Infrastructures Ltd. · ISO 14064-1 & ICAI SAE 3410 Assured', 34, 17);

  // Document Title Banner
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text(title, 14, 38);

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(subtitle, 14, 44);
  }

  // Horizontal divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 47, 196, 47);
}

// Helper to draw Footer
function drawMeilFooter(doc, sha256) {
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 18, 196, pageHeight - 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Confidential · For Internal Statutory Audit & SEBI BRSR Reporting Only · Generated by MEIL ESG Enterprise System', 14, pageHeight - 12);

  if (sha256) {
    const truncated = sha256.length > 40 ? sha256.substring(0, 38) + '...' : sha256;
    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(71, 85, 105);
    doc.text(`SHA-256 SEAL: ${truncated}`, 14, pageHeight - 7);
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(22, 163, 74);
  doc.text('✓ ICAI Guideline 2024 Audit Traceable', 150, pageHeight - 7);
}

/**
 * 1. Generate & Download Official Evidence Assurance Record PDF
 */
export function downloadEvidencePDF(docData, extraDetails = {}) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const fileName = docData.fileName || docData.name || 'MEIL_Evidence_Record.pdf';
  const cleanName = fileName.toLowerCase().endsWith('.pdf') ? fileName : `${fileName}.pdf`;

  drawMeilHeader(
    doc,
    'STATUTORY ESG EVIDENCE ASSURANCE RECORD',
    `Audit Dossier Ref: ${extraDetails.voucherNo || docData.relatedRecord || docData.id || 'EV-2026-MEIL'}`
  );

  let y = 53;

  // Status Badge Box
  doc.setFillColor(240, 253, 244); // Light Green
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(14, y, 182, 10, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(22, 163, 74);
  doc.text(`STATUS: ${docData.status || 'VERIFIED'} · SEBI BRSR CORE REASONABLE ASSURANCE READY`, 19, y + 6.5);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Date: ${docData.date || new Date().toLocaleDateString('en-GB')}`, 155, y + 6.5);

  y += 16;

  // Metadata Table Container
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, y, 182, 42, 2, 2, 'FD');

  const metaRows = [
    ['Document File:', fileName, 'Module Category:', docData.moduleDetail || docData.module || 'Energy'],
    ['Related Record:', docData.relatedRecord || 'ESG Log Batch #4921', 'Document Type:', docData.docTypeFull || docData.docType || 'Invoice / Challan'],
    ['Project Site:', docData.project || 'Zojila Tunnel (PKG-2)', 'File Size:', docData.size || '1.8 MB'],
    ['Uploaded By:', docData.uploadedBy || 'Site Officer', 'Upload Timestamp:', docData.uploadedAt || 'Oct 2026']
  ];

  let rowY = y + 7;
  metaRows.forEach(([k1, v1, k2, v2]) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(k1, 18, rowY);
    doc.setTextColor(15, 23, 42);
    doc.text(String(v1).substring(0, 36), 48, rowY);

    doc.setTextColor(100, 116, 139);
    doc.text(k2, 108, rowY);
    doc.setTextColor(15, 23, 42);
    doc.text(String(v2).substring(0, 36), 138, rowY);

    rowY += 9;
  });

  y += 48;

  // Key Audited Value / Metric Card
  doc.setFillColor(240, 249, 255); // Light Sky #F0F9FF
  doc.setDrawColor(186, 230, 253);
  doc.roundedRect(14, y, 182, 30, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(2, 132, 199);
  doc.text('AUDITED QUANTITATIVE RECORD METRIC & SCOPE ALIGNMENT', 18, y + 7);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(12, 74, 110);
  const metricText = extraDetails.quantity || '4,500 Litres HSD (Weighbridge Matched)';
  doc.text(metricText, 18, y + 16);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(3, 105, 161);
  const scopeText = extraDetails.scope || 'BRSR Principle 6 · GHG Scope 1 Stationary Combustion · ISO 14064-1';
  doc.text(scopeText, 18, y + 23);

  y += 36;

  // Assurance Standard Details
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, y, 182, 38, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('ASSURANCE FRAMEWORK & STATUTORY DISCLOSURE COMPLIANCE', 18, y + 8);

  const assurancePoints = [
    `• Standard: ${extraDetails.assuranceStandard || 'ICAI Standard on Assurance Engagements (SAE 3410) & SEBI BRSR Core'}`,
    `• Issuer Authority / Vendor: ${extraDetails.issuer || 'Authorized State Utility / Public Sector Oil Undertaking'}`,
    `• Substation / Facility: ${extraDetails.substation || docData.project || 'Zojila North Portal DG Bank #4'}`,
    `• Primary Telemetry Match: Matched against ERP Weighbridge Batch & Inward Goods Receipt (GRN).`
  ];

  let ptY = y + 15;
  assurancePoints.forEach(pt => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(pt, 18, ptY);
    ptY += 6;
  });

  y += 44;

  // Signatures Container
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(14, y, 88, 30, 2, 2, 'FD');
  doc.roundedRect(108, y, 88, 30, 2, 2, 'FD');

  // Signer 1: Site Lead
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('CERTIFIED & UPLOADED BY', 18, y + 6);
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text(extraDetails.certifiedBy || docData.uploadedBy || 'Rohit Kumar (Site Materials Lead)', 18, y + 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`Digital Sign Timestamp: ${docData.uploadedAt || '04 Oct 2026 10:24 AM'}`, 18, y + 19);
  doc.setTextColor(22, 163, 74);
  doc.text('✓ Identity Authenticated via MEIL SSO', 18, y + 25);

  // Signer 2: Auditor
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('STATUTORY ASSURANCE AUDITOR', 112, y + 6);
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text(extraDetails.verifiedBy || 'K. Venkat (ICAI Qualified ESG Auditor)', 112, y + 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Reasonable Assurance Opinion Issued', 112, y + 19);
  doc.setTextColor(22, 163, 74);
  doc.text('✓ Signed under SAE 3410 Mandate', 112, y + 25);

  y += 36;

  // SHA-256 Hash Box
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(14, y, 182, 14, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('IMMUTABLE CRYPTOGRAPHIC VERIFICATION HASH (SHA-256):', 18, y + 5);
  doc.setFont('courier', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(docData.sha256 || docData.hash || '9f8e7d6c5b4a312019e8d7c6b5a43210fe8b2c1a09d3e4f5a6b7c8d9e0f1a2b3', 18, y + 10);

  // Footer
  drawMeilFooter(doc, docData.sha256 || docData.hash);

  // Trigger real PDF download
  doc.save(cleanName);
}

/**
 * 2. Generate & Download Official Consolidated Report PDF
 */
export function downloadReportPDF(report, kpis = {}) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const safeName = (report.name || 'MEIL_ESG_Report').replace(/[^a-zA-Z0-9_-]/g, '_');
  const cleanName = `${safeName}_${(report.period || '2026').replace(/\s+/g, '_')}.pdf`;

  drawMeilHeader(
    doc,
    report.name || 'MEIL ESG & BRSR CONSOLIDATED REPORT',
    `Category: ${report.type || 'BRSR Comprehensive'} · Period: ${report.period || 'Sep 2026'} · Entity: ${report.project || 'MEIL Group of Companies'}`
  );

  let y = 53;

  // Executive Summary Card
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, y, 182, 32, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('EXECUTIVE STATUTORY SUMMARY', 18, y + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  const summaryLines = doc.splitTextToSize(
    report.summary || 'Consolidated ESG & BRSR statutory disclosures prepared in compliance with SEBI BRSR Core and ICAI SAE 3410 guidance note on reasonable assurance for key enterprise indicators.',
    174
  );
  doc.text(summaryLines, 18, y + 14);

  y += 38;

  // Key Consolidated Metrics Grid
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  doc.text('KEY AUDITED STATUTORY ESG INDICATORS', 14, y);

  y += 5;

  const metrics = [
    { title: 'Total GHG Footprint (Scope 1 + 2)', value: `${kpis.totalGhg_t ?? '1,280.4'} tCO2e`, note: 'Market-based & Location-based' },
    { title: 'Scope 1 Direct Stationary Emissions', value: `${kpis.scope1_t ?? '412.8'} tCO2e`, note: 'Diesel DG Sets & Heavy Machinery' },
    { title: 'Scope 2 Indirect Grid Emissions', value: `${kpis.scope2_t ?? '867.6'} tCO2e`, note: 'CEA India Grid Baseline v19' },
    { title: 'Grid Electricity Consumption', value: `${kpis.gridMwh ?? '1,211.7'} MWh`, note: 'Net-metered HT Substation Bills' },
    { title: 'Water Recycled & Reused Share', value: `${kpis.recycledSharePct ?? '42.5'}%`, note: 'Zero Liquid Discharge (ZLD) Certified' },
    { title: 'Waste Circularity & Co-Processing', value: `${kpis.wasteRecoveryPct ?? '88.2'}%`, note: 'SPCB Hazardous Manifest Cleared' },
    { title: 'Lost Time Incident Rate (LTIFR)', value: `${kpis.ltifr ?? '0.00'}`, note: 'Zero Fatalities · SA8000 Compliant' },
    { title: 'Assurance Readiness Score', value: `${kpis.assuranceScore ?? '98.5'}%`, note: 'Reasonable Assurance Standard Ready' }
  ];

  // Draw 2-column metrics cards
  const cardW = 88;
  const cardH = 18;
  metrics.forEach((m, idx) => {
    const col = idx % 2;
    const row = Math.floor(idx / 2);
    const cx = col === 0 ? 14 : 108;
    const cy = y + (row * (cardH + 4));

    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(cx, cy, cardW, cardH, 2, 2, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(m.title, cx + 5, cy + 5.5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text(m.value, cx + 5, cy + 11.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.8);
    doc.setTextColor(2, 132, 199);
    doc.text(m.note, cx + 5, cy + 15.5);
  });

  y += (Math.ceil(metrics.length / 2) * (cardH + 4)) + 6;

  // Regulatory Compliance Statement
  doc.setFillColor(240, 249, 255);
  doc.setDrawColor(186, 230, 253);
  doc.roundedRect(14, y, 182, 24, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(3, 105, 161);
  doc.text('REGULATORY & AUDIT VERIFICATION NOTICE', 18, y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(71, 85, 105);
  const regLines = doc.splitTextToSize(
    'This report is generated directly from cryptographically hashed primary evidence documents stored within the MEIL ESG Vault. Data conforms to SEBI Circular SEBI/HO/CFD/CMD-2/P/CIR/2021/562, National Guidelines on Responsible Business Conduct (NGRBC), and ICAI SAE 3410 standards.',
    174
  );
  doc.text(regLines, 18, y + 12);

  // Footer
  drawMeilFooter(doc, report.hash || 'sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069');

  doc.save(cleanName);
}

/**
 * 3. Generate & Download Governance Policy PDF
 */
export function downloadPolicyPDF(policy) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const safeName = (policy.title || policy.name || 'MEIL_Policy').replace(/[^a-zA-Z0-9_-]/g, '_');
  const cleanName = `${safeName}_v${policy.version || '1.0'}.pdf`;

  drawMeilHeader(
    doc,
    policy.title || 'CORPORATE GOVERNANCE POLICY',
    `Code: ${policy.code || 'MEIL-POL-2026'} · Version: ${policy.version || 'v2.1'} · Approved by Board of Directors`
  );

  let y = 53;

  // Policy Metadata Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, y, 182, 26, 2, 2, 'FD');

  const items = [
    ['Effective Date:', policy.effectiveDate || '01 Apr 2026', 'Review Frequency:', 'Annual'],
    ['Applicability:', 'All MEIL Group Entities & Subcontractors', 'Compliance Lead:', 'Director - Governance & Compliance']
  ];

  let rY = y + 7;
  items.forEach(([k1, v1, k2, v2]) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(k1, 18, rY);
    doc.setTextColor(15, 23, 42);
    doc.text(v1, 46, rY);

    doc.setTextColor(100, 116, 139);
    doc.text(k2, 108, rY);
    doc.setTextColor(15, 23, 42);
    doc.text(v2, 142, rY);
    rY += 9;
  });

  y += 32;

  // Policy Core Statement
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  doc.text('1. POLICY OBJECTIVE & SCOPE', 14, y);

  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  const desc = policy.description || policy.summary || 'Megha Engineering & Infrastructures Ltd. commits to the highest standards of integrity, environmental stewardship, and human rights across all engineering and infrastructure operations.';
  const descLines = doc.splitTextToSize(desc, 182);
  doc.text(descLines, 14, y);

  y += (descLines.length * 5) + 8;

  // Clauses
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  doc.text('2. STATUTORY DISCLOSURE PRINCIPLES', 14, y);

  y += 6;
  const clauses = [
    '2.1 Zero-tolerance towards corruption, bribery, or non-compliance with statutory environmental permits.',
    '2.2 Full transparency in GHG Scope 1, Scope 2, and Scope 3 disclosures verified under ISO 14064-1.',
    '2.3 Strict alignment with SEBI BRSR Core Principles 1 through 9, ensuring timely grievance redressal.',
    '2.4 Protection of whistleblowers with encrypted and confidential reporting channels.'
  ];

  clauses.forEach(cl => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    doc.text(cl, 14, y);
    y += 7;
  });

  y += 10;

  // Board Stamp Box
  doc.setFillColor(240, 253, 244);
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(14, y, 182, 22, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(22, 163, 74);
  doc.text('OFFICIALLY RATIFIED BY MEIL BOARD ESG COMMITTEE', 18, y + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('Digital Stamp: Authenticated by Corporate Governance Secretariat · Validated for FY 2026-27', 18, y + 15);

  drawMeilFooter(doc, 'sha256:pol9982348a0f12c34d56e78b90a12c34');

  doc.save(cleanName);
}

/**
 * 4. Generic Fallback PDF Generator
 */
export function downloadGenericPDF({ title, filename, lines = [], details = {} }) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const cleanName = filename ? (filename.toLowerCase().endsWith('.pdf') ? filename : `${filename}.pdf`) : 'MEIL_Document.pdf';

  drawMeilHeader(doc, title || 'MEIL STATUTORY ESG RECORD', 'Official Verification Export');

  let y = 55;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);

  lines.forEach(line => {
    if (y > 260) {
      doc.addPage();
      drawMeilHeader(doc, title, 'Continuation Page');
      y = 55;
    }
    const split = doc.splitTextToSize(line, 182);
    doc.text(split, 14, y);
    y += (split.length * 5) + 2;
  });

  drawMeilFooter(doc, details.sha256 || null);
  doc.save(cleanName);
}
